
my own nearest neighbor algorithm
```{r}
#' This function implements the nearest neighbor algorithm.
#'
#' @param Xinput      The training data features as an n x p matrix.
#' @param y_binary    The training data responses as a vector of length n consisting of only 0's and 1's.
#' @param Xtest       The test data that the algorithm will predict on as a n* x p matrix.
#' @return            The predictions as a n* length vector.
nn_algorithm_predict = function(Xinput, y_binary, Xtest){
  best_sqd = Inf #initiate the best squared distance to a huge value
  for(i in 1:nrow(Xinput)) { #loop over rows
    dsqd = 0 #reset distance squared to 0 each time we start looping on a new row
    for(j in 1:ncol(Xinput)) { #loop over columns
      dsqd = dsqd + (Xtest[i, j] - Xinput[i, j])^2 #add the squared distance between Xinput at position i,j and Xtest at i,j
    }
    euclidean_distance = sqrt(dsqd) #calculate the euclidean distance between i'th row of input and test
    if(euclidean_distance < best_sqd) { #if euclidean distance is less than the best_sqd we already have..
      best_sqd = euclidean_distance # set best_sqd equal to the euclidean_distance
      best_row_index = i #keep track of which row has smallest distance
    }
  }
  y_binary[best_row_index]
}
```

A test for the algorithm above
```{r}
Xy = na.omit(MASS::biopsy) #The "breast cancer" data with all observations with missing values dropped
X = Xy[, 2 : 10] #V1, V2, ..., V9
y_binary = as.numeric(Xy$class == "malignant")

xx = nn_algorithm_predict(X, y_binary, X) #fit
```
